# Generated by Django 4.0.3 on 2022-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newuser_who_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='admin_key',
            field=models.IntegerField(default=0),
        ),
    ]
