# Generated by Django 4.0.5 on 2022-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_newuser_admin_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='who_is',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
