# Generated by Django 4.0.3 on 2022-05-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20211014_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='topic',
        ),
    ]
